version: '3'
services:
  api:
    build:
      dockerfile: Dockerfile.dev
      context: ./gringotts-server
    ports:
      - "8000:8000"
    volumes:
      - ./gringotts-server/node_modules:/app/node_modules
      - ./gringotts-server:/app
